# Étape 1 : Construction
FROM node:20-alpine AS builder

# Installer les dépendances pour le build
RUN apk add --no-cache bash git python3 make g++ 

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Étape 2 : Image finale plus légère
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8081

CMD ["npx", "react-native", "start"]