# Utiliser une image Node
FROM node:20-alpine

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Exposer le port
EXPOSE 3000

# Commande pour démarrer le serveur Next.js en mode développement
CMD ["npm", "run", "dev"]
